### PR TITLE
Various minor widgets updates

### PR DESCRIPTION
**Pull request by kernc**
See commit log.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Seems relatively ok. Sometimes I have a hard time moving the centroid. The 'grab' icon is displayed (four directions) upon hover, but the centroid doesn't move. Only works after a couple of clicks.
It also sometimes shows as if I'm about to hold the centroid, but when it fails to do so it adds a new centroid, which is annoying. But I suppose this is outside of this PR.

Can I merge even with the tests failing?

**Comment by kernc** [comment]
> The 'grab' icon is displayed (four directions) upon hover, but the centroid doesn't move.

Still a problem? Can't confirm, though, I changed much in that regard.

> Please rename the PR (K-means updates is uninformative), and move unrelated commits into separate PRs.

Thanks, I was just testing stuff out in order to try to make the CI pass at least ~~most~~some of the time. Wouldn't want to make early conclusions, but at the moment, shit is greeeeen!!! :green_salad:

**Comment by ajdapretnar** [comment]
>     The 'grab' icon is displayed (four directions) upon hover, but the centroid doesn't move.
> 
> Still a problem? Can't confirm, though, I changed much in that regard.

Not in a sense that I can replicate it.
There's another issue with centroids, where I click in the neigbourhood of the centroid (no four directions icon) and when I start dragging, the centroid moves and upon release, a new centroid is created. Totally confusing....
I'm not sure what to do about this, but perhaps we can disallow creating new centroid with a click and allow simply setting the number of centroids and moving them around. However, this might impede teaching k-Means, so @BlazZupan needs to have an input as well. If he's fine with the current state, I'm fine too.

**Comment by BlazZupan** [comment]
I agree with Ajda: let's disallow the creation of new centroids by clicking on the pane.

**Comment by kernc** [comment]
Aware of this issue, I was sadly unable to figure it out in the short while. Opted for the proposed accepted solution instead. Thanks.

**Pull request merged**
