### PR TITLE
JS widgets: don't bridge via QWidget but via thin QObject instead

### PR DESCRIPTION
**Pull request by kernc**
Refs: "WebView/WebEngine: don't permit exposing QWidgets" in https://github.com/biolab/orange3/pull/1799

### CODE REVIEW

**Comment by kernc** [comment]
@PrimozGodec would you have time to have a look at this?

**Comment by PrimozGodec** [comment]
Right now I am only on data with my cellphone. I will check it when I come to some wifi.

**Comment by kernc** [comment]
I don't know why `widgets.tests.test_owgradientdescent.TestOWGradientDescent.test_step_back` stalls on Travis. It passes locally no problem.

**Comment by PrimozGodec** [comment]
I agree with changes. Everything works fine. 

I am still trying to find out what is a problem with Travis. It seems that it is not connected with your changes same happened in https://github.com/biolab/orange3-educational/pull/26.

**Pull request merged**
