### PR TITLE
Random Data: Documentation

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue

Random Data needs documentation.

##### Description of changes
Random Data gets documentation.

##### Includes
- [ ] Code changes
- [ ] Tests
- [X] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@janezd can you check this PR?

**Comment by janezd** [comment]
@ajdapretnar, @PrimozGodec, thanks. I change the last paragraph to add an "for instance" ... and to clarify it a bit.

But now it fails on Travis on Python 3.7 - master. I suppose it's related to Webkit. Does anybody know what's wrong?

**Comment by PrimozGodec** [comment]
It has probably to do something with the latest changes in Orange. We had the same issue in Bioinformatics (Jaka solved it). I will make a PR to solve that tomorrow.

**Comment by PrimozGodec** [comment]
The reason for the issue was that import for report widget changed. I fixed it in https://github.com/biolab/orange3-educational/pull/77

**Pull request merged**
