### PR TITLE
[WIP] Changed color for Educational add-on

### PR DESCRIPTION
**Pull request by PrimozGodec**
Red was too strong it was changed to light yellow.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
ImageAnalytics is yellow as well. I'm not trying to nitpick, but perhaps we can establish a sort of color chart for current and future add-ons in order to avoid same-color add-ons? It just make it much easier to distinguish between them. :smiley:  Same goes for Text Mining and Unsupervised and Prototypes and Data Fusion, but this is already out of the scope of this PR and this add-on. Just something to consider. :smiley:

**Comment by PrimozGodec** [comment]
@ajdapretnar I din't know that ImageAnalytics is yellow. Me and Blaz were discussing that red color that was used before was too strong. Then we decided for yellow, because Blaz gave me idea too google which color usually represents education. There were several ideas but all than yellow are already used in other Orange modules. We can go back to red, but we can use lighter version than before. What do you mean about sth like this #ff9999? @BlazZupan, @ajdapretnar.

**Comment by ajdapretnar** [comment]
Yes, I have all the add-ons imaginable for Orange. :smile: I simulated Timeseries, which has strong blue. I know that particular red was strong, but indeed, since everything else was taken, I decided it is time we go for stronger colors. :grinning:  Here's what we have atm:

add-ons


p.s. I don't mind #ff9999. I don't care very much about the particular shade, only that each add-on has a distinct color. :)

**Comment by ajdapretnar** [comment]
p.p.s. I like the idea that we follow GSoC in terms of colors. Perhaps we can find a different color for ImageAnalytics? Or at least a distinctly different shade of yellow?

**Pull request merged**
