### PR TITLE
Added info box and error bars in the chart

### PR DESCRIPTION
**Pull request by PrimozGodec**
With this pull request we:

* added info box that contains informations about:
    * used regressor
    * RMSE of the regressor
* added error bars in the chart

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@janezd is it enough to have information about used regressor or do I explicitly write something like: "Used regressor from input"

**Comment by janezd** [comment]
The intended use of `gui.label` is

```
        gui.label(
            widget=info_box, master=self,
            label="Root mean square error: %(rmse).6s")
```

It will bind the label to `self.rmse`. In method `apply` you will then have only

        self.rmse = RMSE(predicted)[0]

and the label will change automagically. No need to call `self.rmse_label.setText`, and no need to have `self.rmse_label` stored at all.

**Comment by janezd** [comment]
For the above to work, you will need to add `self.rmse = ""` to `__init__`.

Also, add `self.rmse = ""` to method `clear`, so the number will disappear when the data is gone.

**Comment by janezd** [comment]
Could you rename RMSE to *Root mean square error*?
Also, please compute and show *Mean absolute error* above the *Root mean square error*.

Otherwise, it looks nice -- exactly what we wanted.

**Comment by PrimozGodec** [comment]
Done.

**Pull request merged**
