### PR TITLE
maintenance, tox, github actions

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
https://github.com/biolab/orange3/issues/5145

##### Description of changes
Replace travis with GH actions and add tox configuration.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
#102 will fix errors with Latest.

**Comment by PrimozGodec** [comment]
Regarding SEGFAULTs on Windows. I found out SEGFAULT happens on widgets that use WebView. The same error happens in Time Series (WebView for Highcharts) and I think it will also happen on Text (WordCloud) when other errors will be fixed. Interestingly, it does not happen on Orange3 where WebView is used in several places (e.g. Report widget). 

Does anyone have any idea what might be the reason?

I think that problem might be that some `dll` is missing in the Windows distribution used for testing. I would first try to compare what is the difference (maybe some versions) between runs on Orange3 repo and here. If it does not help I will try to set up a virtual machine with a similar distribution of windows and test there.

**Comment by PrimozGodec** [comment]
Additionaly, if I test it on my Windows server 2012 VM I see following errors but test passes:
```
[6504:6060:0126/043802.230:ERROR:dxva_video_decode_accelerator_win.cc(1399)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)
[6504:6060:0126/043802.230:ERROR:dxva_video_decode_accelerator_win.cc(1399)] DXVAVDA fatal error: could not LoadLibrary: mfplat.dll: The specified module could not be found. (0x7E)
[6504:6060:0126/043802.230:ERROR:dxva_video_decode_accelerator_win.cc(1399)] DXVAVDA fatal error: could not LoadLibrary: msmpeg2vdec.dll: The specified module could not be found. (0x7E)
[6504:6060:0126/043802.230:ERROR:dxva_video_decode_accelerator_win.cc(1407)] DXVAVDA fatal error: could not LoadLibrary: msvproc.dll: The specified module could not be found. (0x7E)
```

I do not know if it has to do anything with the SEGFAULT here. When I googled I found out that it might be due to missing Media Feature Pack, but again the same Windows container is used on Orange3 repo where SEGFAULT does not happen.

**Comment by janezd** [comment]
I merged #102. Rebase this to master now, I guess?

**Comment by PrimozGodec** [comment]
Thank you @janezd. I rebased it and enabled some tests which I disabled before.

**Comment by PrimozGodec** [comment]
I made the last few changes for tests to pass. Now some tests randomly fail due to timeout error onWebViewWidget. I would merge this PR since it is also happening on Travis. It seems timeouts need to be fixed in orange-widget-base.

**Comment by PrimozGodec** [comment]
@janezd can you check this PR?

**Pull request merged**
