### PR TITLE
[FIX] Polynomial Classification: work on sparse

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
Does not work on sparse.

##### Description of changes
Similar as #45 .

Also fix check for `None`.

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-educational/issues/439995362/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-educational/issues/440014395/

**Comment by PrimozGodec** [comment]
Thank you @jerneju. Just noticed today. Works fine.

**Comment by jerneju** [comment]
👍

**Pull request merged**
