### PR TITLE
Random Data: New widget

### PR DESCRIPTION
**Pull request by janezd**
Fixes https://github.com/biolab/orange3/issues/1847 by adding a widget for constructing a data set with variables coming from different (or same) distributions.

It can't construct mixtures, but these can be done easily by concatenating data from a few widgets.

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
@primozgodec, do we want this add-on to be compatible with Orange 3.20? If so, I can work around the missing signal. If not, increase the requirement to 3.21?

**Comment by PrimozGodec** [comment]
I tested the widget and it works great. Should we add the documentation before merging this PR?

**Comment by ajdapretnar** [comment]
Did someone say documentation? 😁

**Comment by janezd** [comment]
Did someone volunteer? 😁

**Comment by janezd** [comment]
I can sketch the text and screenshots, you do the formatting?

**Comment by PrimozGodec** [comment]
@ajdapretnar said she has already prepared most of the documentation. You can check when she pushes the commit.

**Comment by ajdapretnar** [comment]
Documentation available in #75. I am sorry, but I couldn't push to your branch for some reason, so that's the easiest thing.

**Pull request merged**
